services:
  businesscard.api:
    image: businesscard.api
    container_name: "businesscard.api"
    ports:
      - 80
      - 443
    build:
      context: .
      dockerfile: ./Dockerfile
  api_db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "sqlserver2019"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=someThingComplicated1234
